JuliaAlgebra/TypedPolynomials.jl

src/TypedPolynomials.jl, src/abstract/operators.jl, src/abstract/types.jl, src/conversion.jl, src/operators.jl, src/promotion.jl, src/types.jl, test/polynomials.jl
Holy cow, `@pure` is amazing...
=> No more @generated functions in TypedPolynomials

src/TypedPolynomials.jl, src/abstract/operators.jl, src/operators.jl, test/polynomials.jl, test/substitution.jl
@blegat variable=>monomial substitution should work now
=> fix some substitution and iszero bugs

src/abstract/substitution.jl, test/substitution.jl
Back down to zero `@generated` functions after this
=> non-@generated pairzip function

src/TypedPolynomials.jl, src/abstract/types.jl, src/conversion.jl, src/operators.jl, src/types.jl
@blegat this fixes the tests added by https://github.com/rdeits/TypedPolynomials.jl/commit/9cf1d08e69ca89968e745aebd5ccdc05c503c9dc
=> implement some fixes for compatibility with multivariatepolynomials

REQUIRE, src/TypedPolynomials.jl, src/macros.jl, src/types.jl, test/macros.jl, test/runtests.jl
=> new syntax to construct a tuple of variables

src/TypedPolynomials.jl, src/types.jl, test/generators.jl, test/polynomials.jl, test/runtests.jl
=> add and test monomials() function

src/macros.jl, test/macros.jl
=> bracket-constructor macro syntax now creates a tuple

.travis.yml, src/TypedPolynomials.jl, src/abstract/calculus.jl, src/abstract/operators.jl, src/abstract/show.jl, src/abstract/substitution.jl, src/abstract/types.jl, src/call.jl, src/conversion.jl, src/macros.jl, src/operators.jl, src/promotion.jl, src/types.jl, test/jump.jl, test/polynomials.jl, test/promotion.jl, test/runtests.jl, test/show.jl, test/substitution.jl
We can merge the typed branch of MultivariatePolynomials once we agree on these changes.
The `abstract` folder contains things that are specific to TypedPolynomials and StaticPolynomials. The rest has been moved to MultivariatePolynomials.
=> [RFC] Update to implement the API of MultivariatePolynomials

src/operators.jl, src/types.jl, test/jump.jl
Otherwise, it creates a quadratic expression because you promote both polynomials to the AffExpr coefficient type before promoting.
=> Fix multiplication between coeftype Real and coeftype AffExpr

src/operators.jl
per @blegat suggestion in https://github.com/JuliaAlgebra/TypedPolynomials.jl/pull/37#discussion_r172122956
=> remove redundant methods

.travis.yml, README.md, REQUIRE, src/TypedPolynomials.jl, src/operators.jl, src/sequences.jl, test/generators.jl, test/macros.jl, test/polynomials.jl, test/runtests.jl
Locally everything runs without deprecation warnings (using the correpsonding MP branch). My plan is to merge this soon. Cut a release and then reenable the tests in MP to cut there an release. Does this sound ok?
=> Update to 0.7

src/types.jl
See https://github.com/JuliaReach/MathematicalSystems.jl/pull/49#issuecomment-455567684
=> Fix nvariables for vector and types

README.md
=> restore the Readme

.travis.yml, Project.toml, src/TypedPolynomials.jl, src/conversion.jl, src/operators.jl, src/sequences.jl, test/runtests.jl
cc @tweisser @Peiffap @saschatimme
=> Implement MutableArithmetics

src/types.jl
See https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/149
=> Add term method with coef and mono

Project.toml, src/promotion.jl
See https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/165
=> Fix promotion with nonconcrete types

src/promotion.jl
Closes https://github.com/JuliaAlgebra/TypedPolynomials.jl/issues/72
=> Remove duplicate line in promotion

Project.toml
See [this comment](https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/193#issuecomment-1052120652).
=> Add compat for MutableArithmetics v1

src/types.jl
Currently, it ends up in `OutOfMemoryError`
=> Error on negative degree for monomials

src/substitution.jl
Need to pass the new test added in https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/268
=> Fix substitute promotion

.github/workflows/ci.yml, src/operators.jl, src/types.jl
=> Simplify comparison
